"use client";

import { Pause, Play, SkipForward } from "lucide-react";

import { AudioMeters } from "@/components/audio-meters";
import type { QueueItem } from "@/lib/status";

import { trackName } from "./format";

/**
 * Compact host transport: now-playing label, play/pause + skip, the on-stage
 * badge, and the audio meters. Purely presentational — playback state and the
 * transport actions come from props. NOTE: the hidden <audio> decks are NOT
 * here; they stay inline in the parent because their onPlay/onPause/onEnded
 * handlers bind to timing-critical playback refs.
 */
export function HostPlayerCard({
  stageConnected,
  isPlaying,
  current,
  readyCount,
  onPlay,
  onPause,
  onSkip,
}: {
  stageConnected: boolean;
  isPlaying: boolean;
  current: QueueItem | null;
  readyCount: number;
  onPlay: () => void;
  onPause: () => void;
  onSkip: () => void;
}) {
  return (
    <section id="tour-player" className="card rise p-4 sm:p-5">
      <div className="flex items-center justify-between gap-3">
        <div className="flex items-center gap-2.5">
          <p className="eyebrow">Now playing</p>
          {stageConnected && (
            <span className="inline-flex items-center gap-1.5 rounded-full border border-[var(--light-gray)] bg-[var(--cream)] px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.12em] text-[var(--graphite)]">
              <span className="size-1.5 rounded-full bg-[var(--graphite)]" />
              On stage
            </span>
          )}
        </div>
        <AudioMeters active={isPlaying} />
      </div>

      <div className="mt-3 flex items-center gap-3">
        <button
          type="button"
          onClick={isPlaying ? onPause : onPlay}
          disabled={!current?.audioUrl}
          className="btn-primary inline-flex h-10 shrink-0 items-center gap-2 px-5"
        >
          {isPlaying ? <Pause size={17} /> : <Play size={17} />}
          {isPlaying ? "Pause" : "Play"}
        </button>
        <button
          type="button"
          onClick={onSkip}
          disabled={readyCount < 2}
          className="btn-ghost inline-flex h-10 shrink-0 items-center gap-2 px-4"
          title="Next"
        >
          <SkipForward size={17} />
        </button>
        <div className="min-w-0 flex-1">
          <p className="truncate text-sm font-medium text-[var(--graphite)]">
            {current ? trackName(current) : "No ready track selected"}
          </p>
          <p className="truncate text-xs text-[var(--dark-gray)]">
            {current?.requesterName
              ? `Generated by ${current.requesterName}`
              : current
                ? "Anonymous"
                : "Queue is empty"}
            {current?.position ? (
              <span className="mono text-[var(--mid-gray)]">
                {" · #"}
                {current.position}
              </span>
            ) : null}
          </p>
        </div>
      </div>

      {stageConnected ? (
        <p className="mt-3 text-xs text-[var(--mid-gray)]">
          Audio plays from the stage tab — share that tab (with audio) in Zoom.
          These controls drive it.
        </p>
      ) : (
        <p className="mt-3 text-xs text-[var(--mid-gray)]">
          Playing locally on this device — use the transport controls above. Open
          a /stage tab for the big-screen player.
        </p>
      )}
    </section>
  );
}
