import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

export default defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the Vercel Workflow build step.
    "src/app/.well-known/**",
  ]),
  {
    rules: {
      // Intentional patterns in this app: data fetch on mount + polling
      // intervals, and SSR-safe sessionStorage reads after hydration. Keep the
      // signal as a warning rather than failing the build.
      "react-hooks/set-state-in-effect": "warn",
    },
  },
]);
