"use client";

import { useCallback, useEffect, useState } from "react";

import { useRealtimeRefresh } from "@/lib/use-realtime-refresh";
import type { NowPlaying } from "@/lib/status";

export function NowPlayingBanner() {
  const [nowPlaying, setNowPlaying] = useState<NowPlaying | null>(null);

  const refresh = useCallback(async () => {
    try {
      const response = await fetch("/api/now-playing", { cache: "no-store" });
      if (response.ok) {
        setNowPlaying((await response.json()) as NowPlaying);
      }
    } catch {
      // Network blips are non-fatal — keep the last known state.
    }
  }, []);

  useRealtimeRefresh(refresh);

  useEffect(() => {
    refresh();
    const interval = window.setInterval(refresh, 5000);
    return () => window.clearInterval(interval);
  }, [refresh]);

  const track = nowPlaying?.isPlaying ? nowPlaying.track : null;
  if (!track) {
    return null;
  }

  return (
    <section className="rise mb-6">
      <div className="card-soft flex items-center gap-4 p-4 sm:px-5">
        {/* Live equalizer — graphite bars on the light brand surface. */}
        <span
          className="meters flex h-7 w-7 shrink-0 items-end justify-center gap-[3px]"
          aria-hidden="true"
        >
          <span className="h-full w-[3px] rounded-full bg-[var(--graphite)]" />
          <span className="h-full w-[3px] rounded-full bg-[var(--graphite)]" />
          <span className="h-full w-[3px] rounded-full bg-[var(--graphite)]" />
          <span className="h-full w-[3px] rounded-full bg-[var(--graphite)]" />
        </span>

        <div className="min-w-0 flex-1">
          <p className="eyebrow mb-1">Now playing</p>
          <p className="truncate text-base font-medium leading-6 text-[var(--graphite)]">
            {track.prompt}
          </p>
          {track.requesterName && (
            <p className="mt-0.5 truncate text-sm text-[var(--mid-gray)]">
              Generated by {track.requesterName}
            </p>
          )}
        </div>
      </div>
    </section>
  );
}
